require "../Models/model"
# Product.insert(name: "方便", price: "4.5", stock: 30, sale: 1, on_sale: 0, cate_name: "猫粮")
Product.insert(name: "方便面", price: "4.5", stock: 30, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "矿泉水", price: "1.5", stock: 20, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "玫瑰", price: "99", stock: 10, sale: 1, on_sale: 1, cate_id: "flower")
Product.insert(name: "手机贴膜", price: "10", stock: 99, sale: 1, on_sale: 1, cate_id: "server")
Product.insert(name: "方便面", price: "4.5", stock: 30, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "矿泉水", price: "1.5", stock: 20, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "玫瑰", price: "99", stock: 10, sale: 1, on_sale: 1, cate_id: "flower")
Product.insert(name: "手机贴膜", price: "10", stock: 99, sale: 1, on_sale: 1, cate_id: "server")
Product.insert(name: "方便面", price: "4.5", stock: 30, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "矿泉水", price: "1.5", stock: 20, sale: 1, on_sale: 1, cate_id: "foods")
Product.insert(name: "玫瑰", price: "99", stock: 10, sale: 1, on_sale: 1, cate_id: "flower")
Product.insert(name: "手机贴膜", price: "10", stock: 99, sale: 1, on_sale: 1, cate_id: "server")
